name: rhome
description: "Home Automation App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  get_it: ^8.0.3
  http: ^1.3.0
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  path: ^1.9.1
  shared_preferences: ^2.0.0
  sqflite: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons/CustomIcons.ttf
