// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKEAqC1DbmQK7KwswTa7YGvBsgYmCn4k',
    appId: '1:489041474056:web:63a857f8b49eca2a8557bd',
    messagingSenderId: '489041474056',
    projectId: 'rhome-798a8',
    authDomain: 'rhome-798a8.firebaseapp.com',
    storageBucket: 'rhome-798a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZ09PWBnsBEcgKKkrv92EcDBlHUMEnuE',
    appId: '1:489041474056:android:307dca9de1e7ef6b8557bd',
    messagingSenderId: '489041474056',
    projectId: 'rhome-798a8',
    storageBucket: 'rhome-798a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1XZ138f1gQnFjOs9rvLhqfpJaUvXqW6o',
    appId: '1:489041474056:ios:958985c6771ef2d78557bd',
    messagingSenderId: '489041474056',
    projectId: 'rhome-798a8',
    storageBucket: 'rhome-798a8.firebasestorage.app',
    iosBundleId: 'com.rrozian00.rhome',
  );
}
